# Generated by Django 4.2.3 on 2023-08-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="facebook_id",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_pic",
            field=models.ImageField(blank=True, upload_to="profile_pics"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
