# Generated by Django 4.2.3 on 2023-08-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_app", "0003_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(blank=True, max_length=264),
        ),
    ]
