# Generated by Django 4.2.3 on 2023-08-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_app", "0004_userprofile_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
